- import_tasks: install-psycopg2.yml

- name: Create PostgreSQL ANET user
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{anet_db_username}}'
    password: '{{ anet_db_password }}'
    role_attr_flags: SUPERUSER,LOGIN # ToDo check requirements
    state: present

- name: Create ANET database
  become: true
  become_user: postgres
  postgresql_db:
    name: '{{ANET_DB_NAME}}'
    owner: '{{anet_db_username}}'
    encoding: UTF-8
