- import_tasks: install-psycopg2.yml

- name: Create PostgreSQL ANET user
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ANET_DB_USERNAME}}'
    password: '{{ANET_DB_PASSWORD}}'

- name: Create ANET database
  become: true
  become_user: postgres
  postgresql_db:
    name: '{{ANET_DB_NAME}}'
    owner: '{{ANET_DB_USERNAME}}'
    encoding: UTF-8
