# Install PostgreSQL on RedHat 7.x

- set_fact:
    postgresql_rpms:
      - 'postgresql{{postgresql_major_version}}-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'
      - 'postgresql{{postgresql_major_version}}-server-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'
      - 'postgresql{{postgresql_major_version}}-libs-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'
      - 'postgresql{{postgresql_major_version}}-contrib-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'

- name: 'Transfer PostgreSQL RPMs to target machine'
  become: yes
  copy:
    src: '{{local_artifact_folder}}/{{item}}'
    mode: 0644
    dest: '{{remote_rpm_folder}}/'
  loop: "{{postgresql_rpms}}"

- name: 'Install PostgreSQL {{postgresql_major_version}}'
  become: yes
  yum:
    name: "{{ [remote_rpm_folder + '/'] | product(postgresql_rpms) | map('join') | list }}"
    state: present
  register: install_postgresql

- name: Enable PostgreSQL {{postgresql_major_version}} systemd service
  become: yes
  service:
    name: 'postgresql-{{postgresql_major_version}}.service'
    enabled: yes
    daemon_reload: yes

- name: Check if database path exists
  become: yes
  stat:
    path: '/var/lib/pgsql/{{postgresql_major_version}}/data/base'
  register: stat_database

- name: 'Initialize PostgreSQL {{postgresql_major_version}} database'
  become: yes
  command: '/usr/pgsql-{{postgresql_major_version}}/bin/postgresql-{{postgresql_major_version}}-setup initdb'
  register: postgresql_database_initialized
  when: stat_database.stat.exists == False
