# Install PostgreSQL on RedHat 7.x

- name: 'Install latest PostgreSQL {{postgresql_major_version}}'
  become: yes
  yum:
    name:
      - 'postgresql{{postgresql_major_version}}'
      - 'postgresql{{postgresql_major_version}}'
      - 'postgresql{{postgresql_major_version}}'
      - 'postgresql{{postgresql_major_version}}-contrib'
    state: latest
  register: install_postgresql

- name: Enable PostgreSQL {{postgresql_major_version}} systemd service
  become: yes
  service:
    name: 'postgresql-{{postgresql_major_version}}.service'
    enabled: yes
    daemon_reload: yes

- name: Check if database path exists
  become: yes
  stat:
    path: '/var/lib/pgsql/{{postgresql_major_version}}/data/base'
  register: stat_database

- name: 'Initialize PostgreSQL {{postgresql_major_version}} database'
  become: yes
  command: '/usr/pgsql-{{postgresql_major_version}}/bin/postgresql-{{postgresql_major_version}}-setup initdb'
  register: postgresql_database_initialized
  when: stat_database.stat.exists == False
