# Install PostgreSQL on RedHat 7.x

- set_fact:
    postgresql_rpm: 'postgresql{{postgresql_major_version}}-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'
    postgresql_server_rpm: 'postgresql{{postgresql_major_version}}-server-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'
    postgresql_libs_rpm: 'postgresql{{postgresql_major_version}}-libs-{{postgresql_rpm_version}}.rhel7.x86_64.rpm'

- name: 'Transfer PostgreSQL postgresql{{postgresql_major_version}} RPM to target machine'
  become: yes
  copy:
    src: '{{local_artifact_folder}}/{{postgresql_rpm}}'
    mode: 0644
    dest: '{{remote_rpm_folder}}/'

- name: 'Transfer PostgreSQL postgresql{{postgresql_major_version}}-server RPM to target machine'
  become: yes
  copy:
    src: '{{local_artifact_folder}}/{{postgresql_server_rpm}}'
    mode: 0644
    dest: '{{remote_rpm_folder}}/'

- name: 'Transfer PostgreSQL postgresql{{postgresql_major_version}}-libs RPM to target machine'
  become: yes
  copy:
    src: '{{local_artifact_folder}}/{{postgresql_libs_rpm}}'
    mode: 0644
    dest: '{{remote_rpm_folder}}/'

- name: 'Install PostgreSQL {{postgresql_major_version}}'
  become: yes
  yum:
    name:
      - '{{remote_rpm_folder}}/{{postgresql_rpm}}'
      - '{{remote_rpm_folder}}/{{postgresql_server_rpm}}'
      - '{{remote_rpm_folder}}/{{postgresql_libs_rpm}}'
    state: present
  register: install_postgresql

- name: Check if database path exists
  become: yes
  stat:
    path: '/var/lib/pgsql/{{postgresql_major_version}}/data/base'
  register: stat_database

- name: 'Initialize PostgreSQL {{postgresql_major_version}} database'
  become: yes
  command: '/usr/pgsql-{{postgresql_major_version}}/bin/postgresql-{{postgresql_major_version}}-setup initdb'
  register: postgresql_database_initialized
  when: stat_database.stat.exists == False
