- name: Install NGINX reverse proxy

  become: yes
  yum:
    name: nginx
    state: latest

- name: Disable Apache (httpd) systemd service
  become: yes
  service:
    name: httpd
    enabled: no

- name: Enable NGINX systemd service
  become: yes
  service:
    name: nginx
    enabled: yes

- name: Set SE-Linux policy to allow NGINX can connect via HTTP to ANET
  become: yes
  command:
    argv:
      - setsebool
      - -P
      - httpd_can_network_connect
      - on

