- name: Transfer NGINX RPM to target machine
  become: yes
  copy:
    src: '{{local_artifact_folder}}/{{nginx_rpm}}'
    dest: '{{remote_rpm_folder}}/'

- name: Install NGINX {{nginx_rpm}}
  become: yes
  yum:
    name: '{{remote_artifact_folder}}/{{nginx_rpm}}'
    state: present

- name: Enable NGINX systemd service
  become: yes
  service:
    name: nginx
    enabled: yes

- name: Set SE-Linux policy to allow NGINX can connect via HTTP to ANET
  become: yes
  command:
    argv:
      - setsebool
      - -P
      - httpd_can_network_connect
      - on

