- name: Ensure ANET installation folder "{{anet_installation_folder}}" exists
  become: yes
  file:
    path: '{{anet_installation_folder}}'
    state: directory

- name: Transfer and extract ANET on target machine
  become: yes
  unarchive:
    src: '{{local_artifact_folder}}/anet-{{anet_version}}.zip'
    dest: '{{anet_installation_folder}}'

- name: 'Register ANET systemd script'
  become: yes
  template:
    src: anet.service.j2
    dest: '/usr/lib/systemd/system/anet.service'
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Enable & start ANET service
  become: yes
  service:
    name: anet
    enabled: yes
    daemon_reload: yes
