- name: 'Configure Keycloak API access'
  command:
    argv:
      - '{{ keycloak_application_folder }}/bin/kcadm.sh'
      - config
      - credentials
      - --server
      - 'http://localhost:{{ keycloak_http_port }}/auth'
      - --realm
      - '{{ keycloak_api_realm }}'
      - --user
      - '{{keycloak_user}}'
      - --password
      - '{{keycloak_password}}'

- name: 'Create ANET realm: {{ keycloak_anet_realm }}'
  command:
    argv:
      - '{{ keycloak_application_folder }}/bin/kcadm.sh'
      - create
      - realms
      - -s
      - 'realm={{ keycloak_anet_realm }}'
      - -s
      - enabled=true
  register: create_realm
  failed_when:
    - create_realm.rc == 1
    - create_realm.stderr != 'Conflict detected. See logs for details'
  changed_when:
    - create_realm.rc == 0

- name: 'Keycloak client: ANET confidential client (used by the server-side)'
  keycloak_client:
    realm: '{{ keycloak_anet_realm }}'
    auth_client_id: admin-cli
    auth_keycloak_url: '{{ keycloak_auth_url }}'
    auth_realm: '{{ keycloak_api_realm }}' # API realm
    auth_username: '{{ keycloak_user }}'
    auth_password: '{{ keycloak_password }}'
    state: present
    # ANET-Client
    client_id: ANET-Client
    implicit_flow_enabled: no
    standard_flow_enabled: yes
    protocol: openid-connect
    public_client: no
    root_url: 'https://{{ anet_fqhn }}'
    service_accounts_enabled: yes
    base_url: /
    redirect_uris:
      - 'http://{{ anet_fqhn }}/*'
      - /*
    admin_url: ''
    web_origins:
      - +
    secret: '{{ anet_keycloak_key_server }}'
  register: anet_confidential_client_result

- debug:
    var: anet_confidential_client_result
    verbosity: 2

- name: 'Keycloak client: ANET public client (used by client-side)'
  keycloak_client:
    realm: '{{ keycloak_anet_realm }}'
    auth_client_id: admin-cli
    auth_keycloak_url: '{{ keycloak_auth_url }}'
    auth_realm: '{{ keycloak_api_realm }}' # API realm
    auth_username: '{{ keycloak_user }}'
    auth_password: '{{ keycloak_password }}'
    state: present
    # ANET-Client
    client_id: ANET-Client-public
    implicit_flow_enabled: no
    standard_flow_enabled: yes
    protocol: openid-connect
    public_client: yes # Access Type = confidential
    root_url: 'https://{{ anet_fqhn }}'
    service_accounts_enabled: no
    base_url: /
    redirect_uris:
      - 'http://{{ anet_fqhn }}/*'
      - /*
    admin_url: ''
    web_origins:
      - +
  register: anet_public_client_result

- debug:
    var: anet_public_client_result
    verbosity: 2
