- name: 'Configure Keycloak API access'
  command:
    argv:
      - '{{ keycloak_application_folder }}/bin/kcadm.sh'
      - config
      - credentials
      - --server
      - 'http://localhost:{{ keycloak_http_port }}/auth'
      - --realm
      - '{{ keycloak_api_realm }}'
      - --user
      - '{{keycloak_user}}'
      - --password
      - '{{keycloak_password}}'
