- name: 'Install Apache httpd & modules'
  become: yes
  yum:
    name:
      - httpd
      - httpd-tools
      - mod_ssl
      - mod_wsgi # Required for pgAdmin
    state: latest
  register: install_httpd

- name: Retrieve service information
  service_facts:

- name: Disable Apache (httpd) service
  become: yes
  service:
    name: httpd
    enabled: no
  when: ansible_facts.services['httpd.service'] is defined

- name: Enable Apache (httpd) systemd service
  become: yes
  service:
    name: httpd
    enabled: yes

- name: Set SE-Linux policy to allow Apache (httpd) can connect via HTTP to ANET
  become: yes
  command:
    argv:
      - setsebool
      - -P
      - httpd_can_network_connect
      - on

