- name: Retrieve service information
  service_facts:

- name: Stop Apache (httpd) systemd service
  become: yes
  service:
    name: httpd
    state: stopped
  when: ansible_facts.services['httpd.service'] is defined

- name: Start Apache (httpd) systemd service
  become: yes
  service:
    name: httpd
    state: started
