anet-redhat-servers:
  hosts:
    test-ansible-redhat76-01:
      ansible_host: 10.7.41.142
      anet_fqhn: 10.7.41.142
    test-ansible-centos78-01:
      ansible_host: 10.7.41.143
      anet_fqhn: 10.7.41.143
