- name: Create Ansible RPM repository folder exists
  become: yes
  file:
    path: '{{ remote_rpm_repo_folder }}'
    state: directory

- name: 'Update local Ansible repository'
  become: yes
  copy:
    src: '{{ local_rpm_repo_folder }}'
    mode: 0644
    dest: '{{ remote_rpm_repo_folder }}/'
