---
# --------------------------------------------------------------
# Install Java JRE
# --------------------------------------------------------------

- name: Install latest Java 8 JRE
  become: yes
  yum:
    name: 'jre1.8'
    state: latest
