---
# --------------------------------------------------------------
# Install Java JRE
# --------------------------------------------------------------

- name: Install latest Java 8 JRE
  become: yes
  yum:
    name: '{{ jre_rpm_name }}'
    state: latest
