---
# --------------------------------------------------------------
# Install Java JRE
# --------------------------------------------------------------

- name: Install Java JRE
  become: yes
  yum:
    name: 'jre1.8'
    state: present
