remote_rpm_folder: '{{remote_artifact_folder}}'
postgresql_major_version: 12
postgresql_hba_conf_path: '/var/lib/pgsql/{{postgresql_major_version}}/data/pg_hba.conf'
anet_db_username: anet
anet_db_password: Test-P@ssw0rd
ANET_DB_NAME: 'anet'
