# Check Ansible playbook syntax

name: CI Playbook Syntax Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #  Ansible playbook syntax-check
      - name: Run a one-line script
        run: ansible-playbook install-anet.yml --syntax-check

